trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnectionName'  # Replace with your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "✅ Installing Terraform..."
      sudo apt-get update && sudo apt-get install -y unzip curl
      curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      unzip terraform.zip
      sudo mv terraform /usr/local/bin/
      terraform version

      echo "✅ Initializing Terraform..."
      terraform init

      echo "✅ Running Terraform plan..."
      terraform plan -var-file="terraform.tfvars"

      echo "✅ Applying Terraform configuration..."
      terraform apply -auto-approve -var-file="terraform.tfvars"
  displayName: 'Run Terraform CLI'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
