trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(TF_VERSION)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ranjithhdfs'  # <-- change this
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
    displayName: 'Check Azure Connection'

- script: |
    terraform init
    terraform plan -var-file="terraform.tfvars"
  displayName: 'Terraform Init & Plan'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    terraform apply -auto-approve -var-file="terraform.tfvars"
  displayName: 'Terraform Apply'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
